-- =============================================================================
-- GERADO por scripts/gerar-seed.mjs a partir de src/data/catalogo.json.
-- Não edite à mão: altere o JSON e rode `npm run seed`.
-- Rode depois da migration. Pode rodar mais de uma vez: não duplica.
-- Produtos: referências do ranking de vendas do ERP; sort_order = posição no
-- ranking, a home mostra as 10 primeiras.
-- =============================================================================

insert into public.categories (slug, name, image_url, sort_order) values
  ('feminino', 'Feminino', '/images/categorias/feminino.jpg', 1),
  ('masculino', 'Masculino', '/images/categorias/masculino.jpg', 2),
  ('infantil', 'Infantil', '/images/categorias/infantil.jpg', 3)
on conflict (slug) do nothing;

insert into public.collections (slug, name, season, year, headline, description, hero_image_url, hero_mobile_url, gallery_urls, sort_order) values
  ('delicias-de-verao', 'Delícias de Verão', 'verao', 2027, 'Entre pausas gostosas ao ar livre e pequenos momentos do dia a dia.', 'A nova coleção traduz as delícias da estação em peças leves, confortáveis e versáteis para viver o verão com naturalidade.', '/images/colecoes/delicias-campanha.jpg', '/images/colecoes/delicias-campanha-celular.jpg', array['/images/colecoes/delicias-1.jpg', '/images/colecoes/delicias-2.jpg', '/images/colecoes/delicias-3.jpg', '/images/colecoes/delicias-4.jpg']::text[], 1),
  ('entrelacos', 'Coleção Entrelaços', 'inverno', 2026, 'Nossa coleção nasce do encontro entre pessoas, rotinas e histórias.', 'Uma coleção que valoriza o conforto, o ritmo do dia a dia e os momentos simples que criam laços. Tecidos aconchegantes, com estética acolhedora e modelagem pensada para abraçar o corpo.', '/images/colecoes/entrelacos-2.jpg', '/images/colecoes/entrelacos-1.jpg', array['/images/colecoes/entrelacos-3.jpg', '/images/colecoes/entrelacos-1.jpg', '/images/colecoes/entrelacos-4.jpg', '/images/colecoes/entrelacos-2.jpg']::text[], 2)
on conflict (slug) do nothing;

insert into public.products (ref, slug, name, description, category_id, collection_id, is_featured, sort_order)
select v.ref, v.slug, v.name, v.description, c.id, col.id, v.rank <= 10, v.rank
from (values
  ('0810', 'short-doll-regata-mescla-infantil', 'Short doll regata mescla infantil', 'Regata azul estampada com short listrado colorido, conjunto infantil feminino.', 'infantil', 'delicias-de-verao', 1),
  ('0118', 'short-doll-regata-infantil', 'Short doll regata infantil', 'Regata azul com estampa de baleia e short azul-claro liso, conjunto infantil feminino.', 'infantil', 'delicias-de-verao', 2),
  ('0130', 'pijama-bordado-de-manga-masculino', 'Pijama bordado de manga masculino', 'Camiseta de manga curta gola V com bordado no peito e short, em azul-marinho liso.', 'masculino', 'delicias-de-verao', 3),
  ('1043', 'pijama-de-alca-suede-liso', 'Pijama de alça suede liso', 'Blusa de alça fina azul-claro com botões e viés, e short listrado azul e branco, em suede.', 'feminino', 'delicias-de-verao', 4),
  ('0131', 'short-de-malha-masculino', 'Short de malha masculino', 'Short masculino de malha lisa em verde, com cós elástico; modelo sem camisa.', 'masculino', 'delicias-de-verao', 5),
  ('0848', 'pijama-regata-canelado', 'Pijama regata canelado', 'Regata canelada bege com viés marrom e short marrom com cordão no cós.', 'feminino', 'delicias-de-verao', 6),
  ('0115', 'short-doll-de-alca-em-malha', 'Short doll de alça em malha', 'Blusa de alça com estampa "Gelato" e short verde-oliva liso, em malha.', 'feminino', 'delicias-de-verao', 7),
  ('2130', 'pijama-aberto-bordado-de-manga-masculino', 'Pijama aberto bordado de manga masculino', 'Camisa aberta de manga curta com botões e bordado no peito, com short, em azul-claro liso.', 'masculino', 'delicias-de-verao', 8),
  ('0123', 'pijama-aberto-de-manga-bordado', 'Pijama aberto de manga bordado', 'Blusa aberta de manga curta com botões e bermuda, em verde-claro liso.', 'feminino', 'delicias-de-verao', 9),
  ('0550', 'short-liganete-masculino', 'Short liganete masculino', 'Short masculino em liganete azul-marinho estampado, com cós elástico; modelo sem camisa.', 'masculino', 'delicias-de-verao', 10),
  ('1034', 'pijama-de-alca-canelado-listrado', 'Pijama de alça canelado listrado', 'Regata de alça fina e short com cordão na cintura, em malha canelada listrada.', 'feminino', 'delicias-de-verao', 11),
  ('0126', 'camisola-bordada-aberta', 'Camisola bordada aberta', 'Camisola aberta com botões na frente e manga curta, verde-claro lisa, comprimento acima do joelho.', 'feminino', 'delicias-de-verao', 12),
  ('1042', 'pijama-de-alca-suede-feminino', 'Pijama de alça suede feminino', 'Regata de alça fina com estampa no peito e short estampado floral, em suede.', 'feminino', 'delicias-de-verao', 13),
  ('0851', 'pijama-americano-liso', 'Pijama americano liso', 'Camisa de manga curta com gola, botões e vivo rosa, com short combinando, em rosa-claro.', 'feminino', 'delicias-de-verao', 14),
  ('0502', 'short-doll-de-alca-em-liganete', 'Short doll de alça em liganete', 'Conjunto de blusa de alça fina e short em liganete, estampa de tucanos em fundo verde-claro.', 'feminino', 'delicias-de-verao', 15),
  ('0390', 'short-doll-nadador', 'Short doll nadador', 'Conjunto de regata nadador off-white com estampa no peito e short verde estampado de corações.', 'feminino', 'delicias-de-verao', 16),
  ('0080', 'short-doll-com-renda-em-liganete', 'Short doll com renda em liganete', 'Conjunto de blusa de alça fina com renda no decote e short, liso, em liganete azul.', 'feminino', 'delicias-de-verao', 17),
  ('1035', 'pijama-de-alca-canelado-liso', 'Pijama de alça canelado liso', 'Conjunto de blusa de alça com viés branco e short com cordão, liso, em malha canelada marrom.', 'feminino', 'delicias-de-verao', 18),
  ('0355', 'short-doll-regata-canelado', 'Short doll regata canelado', 'Conjunto de regata com detalhe de coração no decote e short com cordão, liso, em malha canelada.', 'feminino', 'delicias-de-verao', 19),
  ('0135', 'short-estampado-masculino-em-malha-pv', 'Short estampado masculino em malha PV', 'Short masculino em malha PV, estampado com âncoras em fundo azul-marinho, cós elástico.', 'masculino', 'delicias-de-verao', 20),
  ('0354', 'short-doll-de-alca-canelado', 'Short doll de alça canelado', 'Conjunto de blusa de alça fina e short com cordão, liso, em malha canelada azul-claro.', 'feminino', 'delicias-de-verao', 21),
  ('0853', 'pijama-americano-curto', 'Pijama americano curto', 'Camisa de manga curta com gola e botões, mais short, em rosa com bolinhas brancas.', 'feminino', 'delicias-de-verao', 22),
  ('0125', 'camisola-bordada-de-manga', 'Camisola bordada de manga', 'Camisola curta de manga curta, lisa, com bordado floral e botões no decote.', 'feminino', 'delicias-de-verao', 23),
  ('0720', 'short-doll-de-alca-estampado', 'Short doll de alça estampado', 'Blusa de alça fina listrada em branco e rosa com short rosa liso.', 'feminino', 'delicias-de-verao', 25),
  ('0350', 'camisola-bordada-aberta-curta', 'Camisola bordada aberta curta', 'Camisola curta de manga curta, aberta na frente com botões e bordado floral no decote.', 'feminino', 'delicias-de-verao', 26),
  ('0300', 'robe-de-seda', 'Robe de seda', 'Robe curto preto acetinado, de manga curta, com faixa para amarrar na cintura.', 'feminino', 'delicias-de-verao', 27),
  ('0716', 'pijama-de-liganete-masculino', 'Pijama de liganete masculino', 'Camiseta de manga curta com estampa no peito e short, em liganete marrom liso.', 'masculino', 'delicias-de-verao', 28),
  ('1036', 'pijama-de-alca-familia-feminino', 'Pijama de alça família feminino', 'Blusa de alça fina com estampa "Oh happy day!" e short com cordão, em azul-marinho.', 'feminino', 'delicias-de-verao', 29),
  ('0110', 'short-doll-regata-em-malha', 'Short doll regata em malha', 'Regata rosa com estampa Pizza Lover Club e short liso vinho, em malha.', 'feminino', 'delicias-de-verao', 30),
  ('0601', 'short-doll-regata-em-liganete', 'Short doll regata em liganete', 'Regata e short em liganete verde com estampa de borboletas e corações.', 'feminino', 'delicias-de-verao', 31),
  ('0129', 'pijama-bordado-regata-masculino', 'Pijama bordado regata masculino', 'Regata e bermuda lisas em cinza, com bordado pequeno no peito.', 'masculino', 'delicias-de-verao', 32),
  ('0501', 'pijama-regata-estampado-em-liganete', 'Pijama regata estampado em liganete', 'Regata e bermuda em liganete azul com estampa de margaridas.', 'feminino', 'delicias-de-verao', 33),
  ('0690', 'pijama-manga-curta-com-pescador', 'Pijama manga curta com pescador', 'Blusa manga curta verde-água com estampa de tulipas e calça pescador azul-marinho.', 'feminino', 'delicias-de-verao', 34),
  ('4130', 'pijama-aberto-com-calca-masculino', 'Pijama aberto com calça masculino', 'Camisa aberta de botões, manga curta com vivo branco, e calça comprida, em verde-oliva.', 'masculino', 'delicias-de-verao', 35),
  ('2134', 'short-doll-regata-estampado', 'Short doll regata estampado', 'Regata branca com estampa floral e bermuda lisa azul-claro.', 'feminino', 'delicias-de-verao', 36),
  ('0310', 'pijama-regata-em-malha', 'Pijama regata em malha', 'Conjunto de regata off-white com bolso estampado e bermuda verde-oliva, em malha.', 'feminino', 'delicias-de-verao', 38),
  ('0316', 'short-doll-nadador-de-onca', 'Short doll nadador de onça', 'Regata nadador verde-água com estampa de tartaruga e flores e short estampado de onça.', 'feminino', 'delicias-de-verao', 41),
  ('0116', 'short-doll-de-alca-de-bolinhas', 'Short doll de alça de bolinhas', 'Blusa de alça fina rosa com estampa de limonada e short vinho de bolinhas, em malha.', 'feminino', 'delicias-de-verao', 42),
  ('2131', 'pijama-regata-floral-em-malha', 'Pijama regata floral em malha', 'Regata azul-claro com decote V e bermuda off-white de estampa floral, em malha.', 'feminino', 'delicias-de-verao', 43),
  ('2226', 'camisola-aberta-xadrez', 'Camisola aberta xadrez', 'Camisola sem manga com abertura frontal de botões e estampa xadrez em tons de rosa.', 'feminino', 'delicias-de-verao', 44),
  ('0330', 'pijama-listrado-de-manga-masculino', 'Pijama listrado de manga masculino', 'Camiseta manga curta cinza mescla com listras pretas e bermuda preta lisa.', 'masculino', 'delicias-de-verao', 45),
  ('0499', 'pijama-bermuda-liganete', 'Pijama bermuda liganete', 'Blusa manga curta rosa com estampa de corações e bermuda vinho lisa, em liganete.', 'feminino', 'delicias-de-verao', 46),
  ('0103', 'pijama-infantil-masculino-em-malha', 'Pijama infantil masculino em malha', 'Conjunto infantil de camiseta manga curta com estampa de futebol e bermuda lisa verde, em malha.', 'infantil', 'delicias-de-verao', 47),
  ('0704', 'short-doll-de-alca', 'Short doll de alça', 'Conjunto de blusa de alça fina com decote V e short azul-marinho com vivo claro e cordão na cintura.', 'feminino', 'delicias-de-verao', 49),
  ('0093', 'camisola-de-alca-liganete-lisa', 'Camisola de alça liganete lisa', 'Camisola curta de alça fina em liganete lisa azul, com decote V e renda no busto.', 'feminino', 'delicias-de-verao', 50),
  ('0122', 'pijama-de-manga-em-malha', 'Pijama de manga em malha', 'Conjunto de blusa manga curta verde-água com estampa de tulipas e bermuda lisa azul-marinho, em malha.', 'feminino', 'delicias-de-verao', 51),
  ('0128', 'pijama-aberto-de-manga-estampado', 'Pijama aberto de manga estampado', 'Conjunto de blusa aberta com botões e manga curta, rosa com estampa floral, e bermuda lisa vinho.', 'feminino', 'delicias-de-verao', 52),
  ('0359', 'short-doll-regata-jovem', 'Short doll regata jovem', 'Conjunto de regata rosa clara estampada e short xadrez rosa com cordão na cintura.', 'feminino', 'delicias-de-verao', 53),
  ('0570', 'pijama-liganete-masculino', 'Pijama liganete masculino', 'Camiseta de manga curta com estampa miúda escura e short liso cinza, em liganete.', 'masculino', 'delicias-de-verao', 54),
  ('0121', 'short-doll-de-alca-infantil', 'Short doll de alça infantil', 'Regata de alça fina com estampa de borboleta e short liso, em verde-água, para menina.', 'infantil', 'delicias-de-verao', 55),
  ('0605', 'camisola-regata-liganete', 'Camisola regata liganete', 'Camisola regata curta em liganete, verde com estampa de flores e corações.', 'feminino', 'delicias-de-verao', 57),
  ('0719', 'pijama-aberto-estampado-de-manga', 'Pijama aberto estampado de manga', 'Blusa de manga curta aberta com botões, azul lisa, e bermuda branca estampada com flores.', 'feminino', 'delicias-de-verao', 58),
  ('0730', 'short-doll-nadador-estampado', 'Short doll nadador estampado', 'Regata nadador listrada em cinza e preto com short liso preto.', 'feminino', 'delicias-de-verao', 59),
  ('2014', 'short-doll-regata-infantil-feminino', 'Short doll regata infantil feminino', 'Regata listrada rosa e branca com babado na barra e short com babados, para menina.', 'infantil', 'delicias-de-verao', 60),
  ('1023', 'pijama-longo-familia-infantil-masculino', 'Pijama longo família infantil masculino', 'Blusa de manga longa azul com estampa e calça xadrez. Linha família, infantil masculina.', 'infantil', 'entrelacos', 62),
  ('1007', 'pijama-longo-familia-infantil-feminino', 'Pijama longo família infantil feminino', 'Blusa de manga longa azul com estampa e calça xadrez. Linha família, infantil feminina.', 'infantil', 'entrelacos', 64),
  ('1024', 'pijama-longo-mescla-infantil-masculino', 'Pijama longo mescla infantil masculino', 'Blusa de manga longa em mescla cinza e calça listrada. Linha infantil masculina.', 'infantil', 'entrelacos', 75),
  ('1021', 'pijama-longo-familia-juvenil-masculino', 'Pijama longo família juvenil masculino', 'Blusa de manga longa azul e calça xadrez, na modelagem juvenil masculina.', 'infantil', 'entrelacos', 85),
  ('1020', 'pijama-longo-familia-juvenil-feminino', 'Pijama longo família juvenil feminino', 'Blusa de manga longa azul e calça xadrez, na modelagem juvenil feminina.', 'infantil', 'entrelacos', 87),
  ('1027', 'pijama-longo-com-laco-feminino', 'Pijama longo com laço feminino', 'Blusa de manga longa bege e calça marrom, em malha macia.', 'feminino', 'entrelacos', 96),
  ('1026', 'pijama-longo-moletinho-feminino', 'Pijama longo moletinho feminino', 'Conjunto de moletinho rosa, com blusa de manga longa estampada e calça.', 'feminino', 'entrelacos', 97),
  ('0990', 'pijama-longo-mescla-feminino', 'Pijama longo mescla feminino', 'Blusa de manga longa em mescla cinza com estampa e calça listrada.', 'feminino', 'entrelacos', 98),
  ('1009', 'pijama-longo-familia-masculino', 'Pijama longo família masculino', 'Blusa de manga longa azul e calça xadrez. Linha família, masculina.', 'masculino', 'entrelacos', 116),
  ('1001', 'pijama-longo-aberto-feminino', 'Pijama longo aberto feminino', 'Camisa de manga longa com botões e calça, em cinza-escuro.', 'feminino', 'entrelacos', 118),
  ('1008', 'pijama-longo-familia-feminino', 'Pijama longo família feminino', 'Blusa de manga longa azul e calça xadrez. Linha família, feminina.', 'feminino', 'entrelacos', 119),
  ('0854', 'camisola-americana-de-malha', 'Camisola americana de malha', 'Camisola de manga curta com botões e gola, em rosa com bolinhas brancas.', 'feminino', 'entrelacos', 121),
  ('1004', 'pijama-longo-plush-liso-feminino', 'Pijama longo plush liso feminino', 'Blusa de manga longa cinza-clara e calça cinza-escura, em plush.', 'feminino', 'entrelacos', 128),
  ('1032', 'pijama-longo-plush-masculino', 'Pijama longo plush masculino', 'Blusa de manga longa e calça em plush, cor grafite. Linha masculina.', 'masculino', 'entrelacos', 131),
  ('1005', 'pijama-longo-aberto-estampado', 'Pijama longo aberto estampado', 'Camisa de manga longa azul-clara estampada com botões e calça marrom.', 'feminino', 'entrelacos', 132),
  ('1033', 'pijama-longo-canelado-feminino', 'Pijama longo canelado feminino', 'Blusa de manga longa listrada e calça azul, em malha canelada.', 'feminino', 'entrelacos', 144),
  ('0852', 'pijama-de-manga-curta-com-calca', 'Pijama de manga curta com calça', 'Blusa de manga curta xadrez rosa com botões e calça combinando.', 'feminino', 'entrelacos', 146),
  ('1031', 'pijama-longo-mescla-liso-feminino', 'Pijama longo mescla liso feminino', 'Blusa de manga longa e calça com cordão no cós, em mescla cinza-escura.', 'feminino', 'entrelacos', 147),
  ('1002', 'pijama-longo-mescla-liso-masculino', 'Pijama longo mescla liso masculino', 'Blusa de manga longa e calça em mescla grafite. Linha masculina.', 'masculino', 'entrelacos', 167),
  ('0223', 'pijama-de-calca-canelado-estampado', 'Pijama de calça canelado estampado', 'Blusa de manga curta azul-clara estampada e calça, em malha canelada.', 'feminino', 'entrelacos', 170),
  ('1025', 'pijama-listrado-masculino', 'Pijama listrado masculino', 'Camiseta de manga curta listrada e calça cinza. Linha masculina.', 'masculino', 'entrelacos', 195),
  ('1003', 'pijama-liso-feminino', 'Pijama liso feminino', 'Blusa de manga curta rosa com botões e calça combinando.', 'feminino', 'entrelacos', 205),
  ('0222', 'pijama-de-calca-canelado-liso', 'Pijama de calça canelado liso', 'Blusa de manga curta azul-clara e calça, em malha canelada lisa.', 'feminino', 'entrelacos', 206),
  ('0981', 'pijama-longo-infantil-feminino', 'Pijama longo infantil feminino', 'Blusa de manga longa cinza com estampa e calça listrada. Linha infantil feminina.', 'infantil', 'entrelacos', 900),
  ('0015', 'camisola-de-alca-estampada-gelato', 'Camisola de alça estampada gelato', 'Camisola de alça fina off-white com estampa de taça de sorvete e a palavra Gelato, com viés verde-militar na gola e nas alças.', 'feminino', 'delicias-de-verao', 901),
  ('0070', 'short-doll-de-alca-com-renda', 'Short doll de alça com renda', 'Blusa de alça rosa lisa com renda no decote e short liso na mesma cor rosa.', 'feminino', 'delicias-de-verao', 902),
  ('0072', 'camisola-de-alca-lisa-com-renda', 'Camisola de alça lisa com renda', 'Camisola de alça fina rosa lisa, com detalhe de renda no decote e fenda lateral na barra.', 'feminino', 'delicias-de-verao', 903),
  ('0083', 'camisola-aberta-estampada-de-coracao', 'Camisola aberta estampada de coração', 'Camisola sem manga abotoada na frente, azul com estampa de corações em tons de azul e branco.', 'feminino', 'delicias-de-verao', 904),
  ('0085', 'pijama-regata-gola-v-com-bermuda', 'Pijama regata gola V com bermuda', 'Regata verde-água lisa com gola V e bermuda azul-marinho estampada de corações brancos.', 'feminino', 'delicias-de-verao', 905),
  ('0086', 'pijama-manga-curta-estampa-de-coracao', 'Pijama manga curta estampa de coração', 'Blusa de manga curta e calça comprida no mesmo tecido mescla escuro, com estampa de corações brancos.', 'feminino', 'delicias-de-verao', 906),
  ('0087', 'camisola-aberta-estampa-de-coracoes', 'Camisola aberta estampa de corações', 'Camisola de manga curta abotoada na frente, rosa com estampa de corações brancos.', 'feminino', 'delicias-de-verao', 907),
  ('0088', 'pijama-aberto-floral-manga-curta', 'Pijama aberto floral manga curta', 'Blusa de manga curta abotoada na frente com gola V e short combinando, em rosa com estampa floral miúda branca.', 'feminino', 'delicias-de-verao', 908),
  ('0091', 'camisola-de-alca-poa-com-renda', 'Camisola de alça poá com renda', 'Camisola de alça fina preta com estampa de poá branco e renda preta no decote em V.', 'feminino', 'delicias-de-verao', 909),
  ('0094', 'camisola-regata-estampada-com-botoes', 'Camisola regata estampada com botões', 'Camisola sem manga azul-marinho mesclada com estampa de beija-flores rosas e folhas verdes, com abertura de botões no decote.', 'feminino', 'delicias-de-verao', 910),
  ('0102', 'pijama-estampado-game-infantil', 'Pijama estampado game infantil', 'Camiseta de manga curta bordô mescla com estampa de controle de videogame e short listrado em bordô e branco.', 'infantil', 'delicias-de-verao', 911),
  ('0104', 'short-doll-regata-game-infantil', 'Short doll regata game infantil', 'Regata vinho mescla com estampa de controle de videogame e short listrado vinho e branco, conjunto infantil masculino.', 'infantil', 'delicias-de-verao', 912),
  ('0107', 'short-doll-regata-estampado-0107', 'Short doll regata estampado', 'Regata azul com estampa escrita e peixe no peito e vivo rosa, com short estampado azul-claro e cordão na cintura.', 'feminino', 'delicias-de-verao', 913),
  ('0108', 'samba-cancao-estampado-infantil', 'Samba-canção estampado infantil', 'Short samba-canção de cetim azul-marinho com estampa geométrica em vermelho e rosa, com elástico na cintura.', 'infantil', 'delicias-de-verao', 914),
  ('0109', 'short-doll-regata-estampado-0109', 'Short doll regata estampado', 'Regata rosa-claro com viés vinho e estampa de garrafa de limonada com frutas, e short vinho com poá de bolinhas e corações.', 'feminino', 'delicias-de-verao', 915),
  ('0111', 'camisola-regata-rosa-estampada', 'Camisola regata rosa estampada', 'Camisola regata rosa-claro com viés vinho no decote e cavas e estampa de pizza na frente.', 'feminino', 'delicias-de-verao', 916),
  ('0114', 'short-doll-regata-estampado-infantil', 'Short doll regata estampado infantil', 'Regata azul com escrita estampada no peito e short azul-claro com estampa de ondas e óculos de sol, conjunto infantil feminino.', 'infantil', 'delicias-de-verao', 917),
  ('0119', 'short-doll-de-alca-estampado-infantil', 'Short doll de alça estampado infantil', 'Regata de alça rosa claro com estampa de limonada e acabamento rendado no decote, com short bordô de poás e coraçõezinhos.', 'infantil', 'delicias-de-verao', 918),
  ('0124', 'short-doll-estampa-de-baleias-infantil', 'Short doll estampa de baleias infantil', 'Camiseta de manga curta rosa claro com estampa de baleias e frase, com short rosa liso, conjunto infantil feminino.', 'infantil', 'delicias-de-verao', 919),
  ('0139', 'short-doll-regata-infantil-0139', 'Short doll regata infantil', 'Regata azul-claro com estampa de carros de corrida e short azul liso, conjunto infantil masculino.', 'infantil', 'delicias-de-verao', 920),
  ('0203', 'pijama-estampado-dinossauro-infantil', 'Pijama estampado dinossauro infantil', 'Camiseta de manga curta azul-clara estampada com dinossauros em azul-marinho e short combinando na mesma estampa.', 'infantil', 'delicias-de-verao', 921),
  ('0216', 'short-doll-de-alca-estampado-0216', 'Short doll de alça estampado', 'Regata de alça fina verde-água com estampa de tartaruga e flores rosas, e short verde-água com estampa manchada.', 'feminino', 'delicias-de-verao', 922),
  ('0219', 'short-doll-de-alca-tartaruga-infantil', 'Short doll de alça tartaruga infantil', 'Regata de alça verde-água com estampa de tartaruga e flores rosa, com short estampado no mesmo tom.', 'infantil', 'delicias-de-verao', 923),
  ('0239', 'short-doll-regata-dinossauros-infantil', 'Short doll regata dinossauros infantil', 'Regata e short em azul-claro com estampa de dinossauros em azul-marinho, conjunto infantil masculino.', 'infantil', 'delicias-de-verao', 924),
  ('0301', 'robe-liso-transpassado', 'Robe liso transpassado', 'Robe azul-marinho liso, transpassado com amarração na lateral e manga curta ampla.', 'feminino', 'delicias-de-verao', 925),
  ('0304', 'pijama-de-manga-curta-masculino', 'Pijama de manga curta masculino', 'Camiseta de manga curta bege com estampa de tartaruga no peito e bermuda azul-marinho estampada com veleiros.', 'masculino', 'delicias-de-verao', 926),
  ('0305', 'pijama-de-manga-curta-infantil', 'Pijama de manga curta infantil', 'Camiseta de manga curta bege com estampa de tartaruga no peito e short azul-marinho estampado com barcos, conjunto infantil masculino.', 'infantil', 'delicias-de-verao', 927),
  ('0306', 'conjunto-regata-tartaruga-infantil', 'Conjunto regata tartaruga infantil', 'Regata bege com estampa de tartaruga no peito e short azul-marinho estampado com veleiros, conjunto infantil masculino.', 'infantil', 'delicias-de-verao', 928),
  ('0307', 'short-doll-regata-com-estampa-marinha', 'Short doll regata com estampa marinha', 'Regata off-white com viés laranja e estampa de tartaruga, onda e conchas, com short azul-marinho estampado de veleiros.', 'feminino', 'delicias-de-verao', 929),
  ('0308', 'short-doll-regata-estampa-marinha', 'Short doll regata estampa marinha', 'Regata off-white com estampa de tartaruga, onda e conchas, com short azul-marinho estampado de veleiros.', 'feminino', 'delicias-de-verao', 930),
  ('0309', 'short-doll-regata-estampa-marinha-infantil', 'Short doll regata estampa marinha infantil', 'Regata off-white com estampa de tartaruga, onda e conchas, com short azul-marinho estampado de barcos.', 'infantil', 'delicias-de-verao', 931),
  ('0329', 'pijama-regata-listrado-masculino', 'Pijama regata listrado masculino', 'Regata cinza-mescla com listras brancas e bermuda verde-água lisa, conjunto masculino.', 'masculino', 'delicias-de-verao', 932),
  ('0358', 'short-doll-de-alca-bordado-xadrez', 'Short doll de alça bordado xadrez', 'Blusa de alça rosa-claro com estampa de meias-luas e bordado no peito, com short xadrez rosa e branco.', 'feminino', 'delicias-de-verao', 933),
  ('0380', 'camisola-regata-bordada-lisa', 'Camisola regata bordada lisa', 'Camisola regata nadador verde-militar lisa com bordado de corações e a frase love yourself no peito.', 'feminino', 'delicias-de-verao', 934),
  ('0402', 'pijama-manga-curta-masculino-estampado', 'Pijama manga curta masculino estampado', 'Camiseta de manga curta azul com frase estampada no peito e bermuda azul-claro com estampa quadriculada.', 'masculino', 'delicias-de-verao', 935),
  ('0403', 'short-doll-regata-estampado-masculino', 'Short doll regata estampado masculino', 'Regata azul com estampa escrita e peixe no peito, com short estampado azul-claro, conjunto masculino.', 'masculino', 'delicias-de-verao', 936),
  ('0404', 'pijama-bordado-peixe-infantil', 'Pijama bordado peixe infantil', 'Camiseta de manga curta azul com bordado de peixe e letras no peito, com bermuda estampada em tons de azul-claro e branco.', 'infantil', 'delicias-de-verao', 937),
  ('0407', 'short-doll-regata-infantil-masculino', 'Short doll regata infantil masculino', 'Regata azul com escrita e peixinho estampados, com short azul-claro de estampa quadriculada aquarelada.', 'infantil', 'delicias-de-verao', 938),
  ('0429', 'pijama-regata-mescla-masculino', 'Pijama regata mescla masculino', 'Regata bordô mescla lisa com short listrado em bordô e branco.', 'masculino', 'delicias-de-verao', 939),
  ('0430', 'pijama-de-manga-curta-mescla-masculino', 'Pijama de manga curta mescla masculino', 'Camiseta de manga curta gola careca em mescla vinho com etiqueta no peito e bermuda listrada em vinho e branco.', 'masculino', 'delicias-de-verao', 940),
  ('0500', 'camisola-de-alca-estampada-tucano', 'Camisola de alça estampada tucano', 'Camisola de alça fina verde-claro com estampa de tucanos pretos de bico laranja por toda a peça.', 'feminino', 'delicias-de-verao', 941),
  ('0582', 'pijama-regata-estampado-com-bermuda', 'Pijama regata estampado com bermuda', 'Regata verde-água estampada de borboletas e corações com renda no decote V, e bermuda verde lisa.', 'feminino', 'delicias-de-verao', 942),
  ('0590', 'pijama-pescador-regata-estampado', 'Pijama pescador regata estampado', 'Regata off-white com estampa de flores e abertura de botões no decote, com calça pescador salmão lisa.', 'feminino', 'delicias-de-verao', 943),
  ('0650', 'camisola-listrada-com-botoes', 'Camisola listrada com botões', 'Camisola de manga curta listrada em vermelho e branco, com abertura de botões azuis no decote.', 'feminino', 'delicias-de-verao', 944),
  ('0702', 'camisola-de-alca-com-vies', 'Camisola de alça com viés', 'Camisola de alça azul-marinho lisa com estampa escrita no peito e viés branco no decote e na barra.', 'feminino', 'delicias-de-verao', 945),
  ('0703', 'camisola-regata-lisa-com-vies', 'Camisola regata lisa com viés', 'Camisola regata rosa lisa com a palavra inspire escrita no peito e viés azul-marinho na gola, nas cavas e na barra.', 'feminino', 'delicias-de-verao', 946),
  ('0706', 'short-doll-de-manga-curta-estampado', 'Short doll de manga curta estampado', 'Camiseta de manga curta verde claro com escrita e flor estampadas e viés azul-marinho, com short da mesma cor com cordão.', 'feminino', 'delicias-de-verao', 947),
  ('0710', 'camisola-de-alca-listrada', 'Camisola de alça listrada', 'Camisola de alça fina branca com listras rosa e acabamento rosa liso no decote e nas alças.', 'feminino', 'delicias-de-verao', 948),
  ('0714', 'pijama-xadrez-manga-curta', 'Pijama xadrez manga curta', 'Camiseta de manga curta xadrez em rosa, branco e bege com short combinando de cordão na cintura.', 'feminino', 'delicias-de-verao', 949),
  ('0715', 'camisola-manga-curta-listrada', 'Camisola manga curta listrada', 'Camisola de manga curta listrada em vermelho e branco, com vivo azul-marinho nas laterais.', 'feminino', 'delicias-de-verao', 950),
  ('0750', 'short-doll-de-alca-borboleta', 'Short doll de alça borboleta', 'Regata de alça verde-água mescla com estampa de borboletas rosa e azul, com short rosa liso.', 'feminino', 'delicias-de-verao', 951),
  ('0760', 'short-doll-regata-borboletas', 'Short doll regata borboletas', 'Regata verde-água mescla com estampa de borboletas rosa e azul e short rosa liso.', 'feminino', 'delicias-de-verao', 952),
  ('0770', 'camisola-regata-nadador-mescla', 'Camisola regata nadador mescla', 'Camisola regata de cavas nadador em rosa mescla, lisa, com viés vinho na gola e nas cavas.', 'feminino', 'delicias-de-verao', 953),
  ('0800', 'short-doll-regata-mescla-listrado', 'Short doll regata mescla listrado', 'Regata rosa mescla com short listrado em rosa, cinza e azul.', 'feminino', 'delicias-de-verao', 954),
  ('0815', 'short-doll-de-alca-estampado-juvenil', 'Short doll de alça estampado juvenil', 'Regata de alça verde-água com estampa escrita no peito e elástico na barra, com short listrado em cinza, azul e verde-água.', 'infantil', 'delicias-de-verao', 955),
  ('0816', 'short-doll-regata-juvenil-estampado', 'Short doll regata juvenil estampado', 'Regata azul-clara com estampa floral e letras no peito, com short listrado em coral, azul e cinza.', 'infantil', 'delicias-de-verao', 956),
  ('0819', 'pijama-de-manga-curta-xadrez', 'Pijama de manga curta xadrez', 'Blusa de manga curta e short em xadrez rosa e branco, com cordão de amarrar na cintura.', 'infantil', 'delicias-de-verao', 957),
  ('0841', 'short-doll-de-alca-listrado', 'Short doll de alça listrado', 'Regata de alça verde-água com estampa pequena no peito e short listrado em azul, verde e mescla.', 'feminino', 'delicias-de-verao', 958),
  ('0845', 'short-doll-regata-listrado', 'Short doll regata listrado', 'Regata azul-claro com estampa floral e escrita no peito e short listrado em coral, azul e cinza.', 'feminino', 'delicias-de-verao', 959),
  ('0901', 'short-doll-regata-com-camera-estampada', 'Short doll regata com câmera estampada', 'Regata bege com estampa de câmera fotográfica e frase, com short listrado azul-marinho e branco.', 'feminino', 'delicias-de-verao', 960),
  ('0911', 'short-doll-de-alca-estampado-0911', 'Short doll de alça estampado', 'Regata de alça fina rosa-claro com estampa de câmera fotográfica e letras, com short listrado azul-marinho e branco.', 'feminino', 'delicias-de-verao', 961),
  ('1010', 'pijama-estampado-futebol-infantil', 'Pijama estampado futebol infantil', 'Camiseta de manga curta creme com estampa de bola de futebol e letras no peito, com short verde-militar liso.', 'infantil', 'delicias-de-verao', 962),
  ('1011', 'pijama-regata-estampado-infantil-masculino', 'Pijama regata estampado infantil masculino', 'Regata azul-claro com estampa de etiquetas e frases no peito, e short azul liso.', 'infantil', 'delicias-de-verao', 963),
  ('1012', 'pijama-regata-mescla-infantil', 'Pijama regata mescla infantil', 'Regata bordô mescla com estampa escrita no peito e short listrado em bordô e branco.', 'infantil', 'delicias-de-verao', 964),
  ('1013', 'pijama-de-manga-curta-mescla-infantil', 'Pijama de manga curta mescla infantil', 'Camiseta de manga curta em mescla vinho com estampa no peito e bermuda listrada em vinho e branco, conjunto infantil masculino.', 'infantil', 'delicias-de-verao', 965),
  ('1037', 'pijama-manga-curta-liso-masculino', 'Pijama manga curta liso masculino', 'Camiseta de manga curta azul-marinho com frase estampada no peito e short azul-marinho com faixa clara na lateral.', 'masculino', 'delicias-de-verao', 966),
  ('1038', 'short-doll-de-alca-infantil-1038', 'Short doll de alça infantil', 'Regata de alça azul-marinho com estampa escrita e coração bordado, com short azul-marinho de faixa lateral azul-claro e cordão na cintura.', 'infantil', 'delicias-de-verao', 967),
  ('1039', 'pijama-estampado-manga-curta-infantil', 'Pijama estampado manga curta infantil', 'Camiseta de manga curta azul-marinho com estampa de carinha e letras no peito, com short azul-marinho de faixa lateral azul-clara.', 'infantil', 'delicias-de-verao', 968),
  ('1040', 'short-doll-de-alca-bordado', 'Short doll de alça bordado', 'Regata de alça fina azul-marinho com bordado de frase e coração, e short combinando com faixa branca na lateral e cordão.', 'infantil', 'delicias-de-verao', 969),
  ('1041', 'pijama-manga-curta-azul-marinho-infantil', 'Pijama manga curta azul-marinho infantil', 'Camiseta de manga curta azul-marinho com estampa pequena no peito e short azul-marinho com listra branca lateral.', 'infantil', 'delicias-de-verao', 970)
) as v(ref, slug, name, description, category_slug, collection_slug, rank)
join public.categories c on c.slug = v.category_slug
left join public.collections col on col.slug = v.collection_slug
on conflict (slug) do nothing;

insert into public.product_images (product_id, url, alt, sort_order)
select p.id, '/images/produtos/' || p.ref || '.jpg', p.name || ', ref. ' || p.ref, 1
from public.products p
where p.ref in ('0810', '0118', '0130', '1043', '0131', '0848', '0115', '2130', '0123', '0550', '1034', '0126', '1042', '0851', '0502', '0390', '0080', '1035', '0355', '0135', '0354', '0853', '0125', '0720', '0350', '0300', '0716', '1036', '0110', '0601', '0129', '0501', '0690', '4130', '2134', '0310', '0316', '0116', '2131', '2226', '0330', '0499', '0103', '0704', '0093', '0122', '0128', '0359', '0570', '0121', '0605', '0719', '0730', '2014', '1023', '1007', '1024', '1021', '1020', '1027', '1026', '0990', '1009', '1001', '1008', '0854', '1004', '1032', '1005', '1033', '0852', '1031', '1002', '0223', '1025', '1003', '0222', '0981', '0015', '0070', '0072', '0083', '0085', '0086', '0087', '0088', '0091', '0094', '0102', '0104', '0107', '0108', '0109', '0111', '0114', '0119', '0124', '0139', '0203', '0216', '0219', '0239', '0301', '0304', '0305', '0306', '0307', '0308', '0309', '0329', '0358', '0380', '0402', '0403', '0404', '0407', '0429', '0430', '0500', '0582', '0590', '0650', '0702', '0703', '0706', '0710', '0714', '0715', '0750', '0760', '0770', '0800', '0815', '0816', '0819', '0841', '0845', '0901', '0911', '1010', '1011', '1012', '1013', '1037', '1038', '1039', '1040', '1041')
  and not exists (select 1 from public.product_images i where i.product_id = p.id);
